
version: '3.1'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: s21003
      MYSQL_DATABASE: befit
      MYSQL_USER: konewka
      MYSQL_PASSWORD: wiaderko
    ports:
      - "3306:3306"