version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: befit
      POSTGRES_USER: konewka
      POSTGRES_PASSWORD: wiaderko
    ports:
      - "5432:5432"
